Algoritmo "Calculando a área do circulo"
// Disciplina   : [Linguagem de Programação com JavaScript]
// Professor   : Jailson (jájá) (Obama)
// Descrição   : Este algoritmo irá calcular a área de um círculo
// Autor(a)    : Campelo
// Data atual  : 28/08/2024
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo