Algoritmo "semnome"
// Disciplina   : [Linguagem de Programação com JavaSricpt]
// Professor   : Jailson (Jaja)
// Descrição   : Algoritmo para ler uma temperatura em graus Fahrenheit,
//calcular e escrever o valor correspondente em graus Celsius
// Autor(a)    : Campelo
// Data atual  : 03/09/2024
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo